function post_proc_fig_box

% Code for post processing boxplots
% 
% Written by: Ahmed Abdul Quadeer 
% Last updated: 2018-04-07

set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.01 .01] , ...%'XMinorTick'  , 'off'      , ...'YMinorTick'  , 'on'      , ...
    'XColor'      , [.1 .1 .1], ...
    'YColor'      , [.1 .1 .1], ...%    'YTick'       , 0:5:30,...   
    'XTick'       , 1:1:100,...   
    'YTick'       , 0:2:14,...
    'LineWidth'   , .5        );